projects:
  personalbpb-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: mjwzxudjj5fchjq2imnoa6scoi
        maxDepth: 2
extensions:
  amplify:
    version: 3
